services:
  database:
    image: postgres:15
    env_file:
      - .env
    ports:
      - ${postgres_port}:5432
    environment:
      - POSTGRES_DB=${postgres_db}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_HOST=${postgres_host}
      - POSTGRES_PORT=${postgres_port}
  redis:
    image: redis:7
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - REDIS_PORT=${redis_port}
      - REDIS_USER=${redis_user}
      - REDIS_PASSWORD=${redis_password}
      - REDIS_HOST=${redis_host}
