services:
  database:
    image: postgres:15
    env_file:
      - .env
    ports:
      - ${postgres_port}:5432
  redis:
    image: redis:7
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379