services:
  database:
    image: postgres:15
    env_file:
      - .env
    ports:
      - ${postgres_port}:5432
    environment:
      - POSTGRES_DB=${postgres_db}
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
      - POSTGRES_HOST=${postgres_host}
      - POSTGRES_PORT=${postgres_port}