services:
  database:
    image: postgres:16
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
  redis:
    image: redis:7
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379