services:
  database:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
  redis:
    container_name: redis
    image: redis:7
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
  monitoring:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000