"""products

Revision ID: 0b42b855e620
Revises: 2681df47a368
Create Date: 2023-07-30 15:02:47.395853

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0b42b855e620'
down_revision = '2681df47a368'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('cost', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('post', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created')
    op.drop_table('product')
    # ### end Alembic commands ###
