"""image_id

Revision ID: 46a65fb29c4c
Revises: 0b42b855e620
Create Date: 2023-08-01 19:52:23.211333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a65fb29c4c'
down_revision = '0b42b855e620'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_id')
    # ### end Alembic commands ###
